### PR TITLE
Adding the possibility to use a custom theme

### PR DESCRIPTION
**Pull request by VittoriDavide**
Making possible to pass the theme to the Alert Builder

### CODE REVIEW

**Comment by SuddenH4X** [comment]
Hi @VittoriDavide,

thanks for your PR!

I have one question: In which case do you need to set a custom theme? The app's theme should be used per default. Isn't that working for you?

And if this is really not enough you could use the `create()` method of the builder to get the `DialogFragment`. With this you can use the method `setStyle()` to overwrite it.

**Comment by VittoriDavide** [comment]
Hi @SuddenH4X,

Thank you for your feedback, and the library! 

Yes, I am aware that the app default theme is used on the Dialog, and it works pretty well. The only thing is that I needed for this particular Dialog to set a custom color for the buttons. also

I wanted additionally that the library showed the dialog under the determined conditions that it handles, but when I `create()`  I have the object of the `DialogFragment` and I am not able to pass it back to the library so it can show it when is necessary.

I think passing the theme to the constructors of `DialogFragment` is a helpful feature to have. What do you think?

**Comment by SuddenH4X** [comment]
Hi @VittoriDavide,

please excuse the long delays. I have no time atm. But I think your changes are useful and in ~2 weeks I will look into that. Thanks in advance!

**Comment by SuddenH4X** [comment]
Will be merged with #43

**Pull request closed without merging**
